// 例: src/lib/iros/soul/individuality.ts

export const IROS_SOUL_INDIVIDUALITY_V1 = {
  principles: [
    '個性は「直すべき欠陥」ではなく、「存在理由に直結する偏り・才能」として扱う。',
    '偏りは、その人が担う役割やフィールドの方向を示すコンパスである。',
    '他者との比較ではなく、「その人固有の軌道」の中で意味づける。',
    '不便さや生きづらさも、守ろうとした結果としてまず尊重する。',
    '本人の準備ができる前にラベルを押し付けず、「気づきの余白」を残す。'
  ],

  reframes: [
    /* ========== Ⅰ. Emotion（感情系） ========== */
    { category: 'emotion', trait: '怖がり', meaning: '危険をいち早く察知し、自分や周囲を守るためのセンサー。' },
    { category: 'emotion', trait: '不安になりやすい', meaning: '未来のリスクを事前に想像できる、予測と備えの才能。' },
    { category: 'emotion', trait: '傷つきやすい', meaning: '人や場の微細な変化を感じ取れる、高感度な共鳴アンテナ。' },
    { category: 'emotion', trait: '怒りっぽい', meaning: '不正や理不尽を見逃さない、変化と改善のエンジン。' },
    { category: 'emotion', trait: 'さみしがり', meaning: 'つながりや絆を大切にできる、関係性の守り手。' },
    { category: 'emotion', trait: '気にしすぎ', meaning: '細やかな配慮で場を整えられる、空気のデザイナー。' },
    { category: 'emotion', trait: '感情の波が激しい', meaning: 'ドラマや表現を生み出せる、豊かな感性の持ち主。' },
    { category: 'emotion', trait: '感情が薄いと言われる', meaning: '状況を冷静に見つめられる、クールな観察者。' },
    { category: 'emotion', trait: '涙もろい', meaning: '他者の物語に深く共感できる、共振の才能。' },
    { category: 'emotion', trait: '緊張しやすい', meaning: '場や相手を大切にしているからこそ、真剣に向き合える人。' },
    { category: 'emotion', trait: '心配性', meaning: '最悪のケースを想定し、備えを整えられる安全管理者。' },
    { category: 'emotion', trait: 'ショックを引きずりやすい', meaning: '出来事の意味を深く受け止められる、真面目な受信者。' },
    { category: 'emotion', trait: '罪悪感を抱えやすい', meaning: '他者や影響をちゃんと考えられる、責任感の強い心。' },
    { category: 'emotion', trait: '恥ずかしがり', meaning: '自分や相手を丁寧に大事にしたい、繊細な感性。' },
    { category: 'emotion', trait: '寂しさを隠してしまう', meaning: '人を心配させたくない、思いやりの深い優しさ。' },
    { category: 'emotion', trait: '人前で弱音を吐けない', meaning: '場を乱したくない、支え役としての責任感。' },
    { category: 'emotion', trait: '怒りを溜め込みやすい', meaning: '関係を壊したくないからこそ、衝突を避けてきた優しさ。' },
    { category: 'emotion', trait: '急に落ち込む', meaning: '内側の変化に敏感で、深いテーマにアクセスしやすい感性。' },
    { category: 'emotion', trait: '気分屋と言われる', meaning: '今この瞬間のエネルギーに素直に反応できるライブ感。' },
    { category: 'emotion', trait: '感情表現がオーバーと言われる', meaning: '場を動かし、物語を生み出せる表現者としての力。' },

    /* ========== Ⅱ. Cognition（思考・認知系） ========== */
    { category: 'cognition', trait: '完璧主義', meaning: 'クオリティと美しさを追求できる、品質保証のプロ。' },
    { category: 'cognition', trait: '優柔不断', meaning: '多方面を見渡してバランスを取れる、中庸の賢者。' },
    { category: 'cognition', trait: '考えすぎる', meaning: '物事を深く掘り下げられる、リサーチと分析の達人。' },
    { category: 'cognition', trait: '論理に偏りがち', meaning: '構造を組み立てられる、ロジックエンジニア。' },
    { category: 'cognition', trait: '空想しすぎる', meaning: 'まだない未来を描ける、イマジネーションの源泉。' },
    { category: 'cognition', trait: '細かいところが気になる', meaning: '見落としを防ぐディテールの番人。' },
    { category: 'cognition', trait: '全体像をつかむのが苦手', meaning: '目の前の一つひとつに丁寧に向き合える人。' },
    { category: 'cognition', trait: '白黒つけたがる', meaning: '曖昧さを整理し、基準をはっきりさせられる役割。' },
    { category: 'cognition', trait: '先の心配ばかりする', meaning: '長期リスクを見通し、備えを提案できる戦略家。' },
    { category: 'cognition', trait: '決めつけがち', meaning: '判断を素早く下せる、意思決定のスピード感。' },
    { category: 'cognition', trait: '人の評価を気にしすぎる', meaning: '周囲の反応を踏まえて調整できる、空気読解のプロ。' },
    { category: 'cognition', trait: '自分のミスを反芻してしまう', meaning: '学びを深く残せる、改善サイクルの保持者。' },
    { category: 'cognition', trait: '新しいことに慎重すぎる', meaning: 'リスクを十分に見極めてから動ける安全装置。' },
    { category: 'cognition', trait: '柔軟に考えにくい', meaning: '芯を貫く一貫性を保てる、ブレない軸。' },
    { category: 'cognition', trait: '優先順位がつけられない', meaning: '多くの可能性を平等に見ていられる広い視野。' },
    { category: 'cognition', trait: '情報を集めすぎて動けない', meaning: '材料を豊富に用意できる、準備のエキスパート。' },
    { category: 'cognition', trait: '自分の考えを疑いすぎる', meaning: '思考の暴走を防ぐ、内なるチェック機構。' },
    { category: 'cognition', trait: '直感を信じきれない', meaning: '感覚と現実をすり合わせようとする調整役。' },
    { category: 'cognition', trait: '自己否定的な解釈をしがち', meaning: '厳しい目線で物事を評価できる、リスク査定の視点。' },
    { category: 'cognition', trait: '同じことをぐるぐる考える', meaning: '一つのテーマを深く磨き続けられる探究者。' },

    /* ========== Ⅲ. Behavior（行動系） ========== */
    { category: 'behavior', trait: '行動が遅い', meaning: '拙速を避け、慎重に最適解を選べる熟考型の実行者。' },
    { category: 'behavior', trait: '先走ってしまう', meaning: '誰よりも早く動き、流れをつくるフロントランナー。' },
    { category: 'behavior', trait: 'めんどくさがり', meaning: '本当に必要なこととそうでないことを見分ける、省エネ設計者。' },
    { category: 'behavior', trait: '三日坊主', meaning: '新しいサイクルを次々と試せる、更新と実験の人。' },
    { category: 'behavior', trait: '衝動買いしてしまう', meaning: '「今ここ」の喜びや直感をすくい上げられる感性。' },
    { category: 'behavior', trait: '先延ばしにしがち', meaning: 'タイミングを見て動こうとする、流れ待ちの感覚。' },
    { category: 'behavior', trait: '仕事を抱え込みやすい', meaning: '責任感が強く、人を守ろうとする引き受け手。' },
    { category: 'behavior', trait: '休むのが下手', meaning: '役割意識が強く、常に支えようとする献身性。' },
    { category: 'behavior', trait: '一度始めると止まれない', meaning: '没頭し続けられる、集中力の塊。' },
    { category: 'behavior', trait: '急に全部やめたくなる', meaning: '古い構造を一気に手放せる、リセットの勇気。' },
    { category: 'behavior', trait: '片付けが苦手', meaning: '目に入るものすべてに意味や記憶を感じ取れる感性。' },
    { category: 'behavior', trait: 'ルーティン化が苦手', meaning: 'その場その場で柔軟に対応できる即興性。' },
    { category: 'behavior', trait: 'スケジュール管理が甘い', meaning: '時間よりも流れや質を重視できる感覚派。' },
    { category: 'behavior', trait: 'ギリギリにならないと動けない', meaning: '集中力を最大限に高められる締切ブースター。' },
    { category: 'behavior', trait: '途中で方向転換しがち', meaning: '新しい可能性を見つけたらすぐ舵を切れる柔軟さ。' },
    { category: 'behavior', trait: '人に頼るのが苦手', meaning: '自分でやりきろうとする自律性・責任感。' },
    { category: 'behavior', trait: '断るのが苦手', meaning: '人を大切にしたい、関係を守ろうとする優しさ。' },
    { category: 'behavior', trait: '途中で飽きてしまう', meaning: '新しい刺激と学びを求める探究心。' },
    { category: 'behavior', trait: '体調管理を後回しにしがち', meaning: '自分より役割を優先してしまう献身性。' },
    { category: 'behavior', trait: '趣味や遊びに偏りすぎる', meaning: '楽しさや喜びを周囲に広げられるムードメーカー。' },

    /* ========== Ⅳ. Social（社会・関係系） ========== */
    { category: 'social', trait: '人見知り', meaning: '誰と深くつながるかを慎重に選べる、縁の選別者。' },
    { category: 'social', trait: '話しすぎる', meaning: '場をあたため、流れをつくるコミュニケーター。' },
    { category: 'social', trait: '話せない', meaning: '相手の話を深く聴ける、静かな傾聴者。' },
    { category: 'social', trait: '空気を読みすぎる', meaning: '場の状態を細かく感じ取れる、調整と和の担い手。' },
    { category: 'social', trait: '依存しやすい', meaning: 'つながりや支え合いを求める、関係深化の達人。' },
    { category: 'social', trait: '距離感が極端', meaning: '安全と安心の境界線を模索している境界感覚の持ち主。' },
    { category: 'social', trait: '嫉妬しやすい', meaning: '本当に欲しいものや大切な価値に気づける心。' },
    { category: 'social', trait: '人を試してしまう', meaning: '関係の本気度を確かめたい、誠実さへの渇望。' },
    { category: 'social', trait: '相手の顔色をうかがう', meaning: '相手の状態を敏感に感じ取れるセンサー。' },
    { category: 'social', trait: '人を信用しきれない', meaning: '危険や裏切りから自分を守るための防衛機能。' },
    { category: 'social', trait: '合わせすぎて疲れる', meaning: '周囲を優先しすぎるほどの思いやりの強さ。' },
    { category: 'social', trait: '相手に踏み込みすぎる', meaning: '深く関わりたい、つながりへの情熱。' },
    { category: 'social', trait: '競争心が強すぎる', meaning: '成長と向上を強く求めるドライブ。' },
    { category: 'social', trait: '謝りすぎる', meaning: '関係を壊したくない、調和を守りたい気持ち。' },
    { category: 'social', trait: '謝れない', meaning: '自分の価値を必死に守ろうとする自己防衛。' },
    { category: 'social', trait: 'SNSに振り回される', meaning: '人とのつながりや反応に敏感なアンテナ。' },
    { category: 'social', trait: '約束にプレッシャーを感じすぎる', meaning: '約束を軽んじたくない、誠実さの表れ。' },
    { category: 'social', trait: '集団が苦手', meaning: '少人数や一対一で深く関わることに向いたスタイル。' },
    { category: 'social', trait: '一対一が苦手', meaning: '多人数の場でこそ力を発揮できるタイプ。' },
    { category: 'social', trait: '目立つと怖くなる', meaning: '注目よりも安心を大切にする、裏方の才能。' },

    /* ========== Ⅴ. Identity（アイデンティティ・存在系） ========== */
    { category: 'identity', trait: '自分が好きじゃない', meaning: '変わりたいと願う力を内側に秘めた、変容の主人公。' },
    { category: 'identity', trait: '自分に厳しすぎる', meaning: '高い基準と使命感を持ったストイックな魂。' },
    { category: 'identity', trait: '自信がない', meaning: '慎重に進みながら、確かな土台を築こうとする途中段階。' },
    { category: 'identity', trait: '自分の軸がわからない', meaning: 'まだどこにでも行ける、探索フェーズの旅人。' },
    { category: 'identity', trait: '何者にもなれていない感覚', meaning: '既存の枠におさまらない、新しい在り方を探す人。' },
    { category: 'identity', trait: '自分だけ浮いている感覚', meaning: '別の視点や世界観を持つ、橋渡し役候補。' },
    { category: 'identity', trait: '人生に意味を見出せないと感じる', meaning: '深い意味や本質を探し続ける哲学者の入り口。' },
    { category: 'identity', trait: '「本当の自分」を隠してしまう', meaning: '本質を安売りしたくない、尊厳を大切にする心。' },
    { category: 'identity', trait: '褒められても受け取れない', meaning: '評価より内側の真実を重んじる感性。' },
    { category: 'identity', trait: '評価に依存しやすい', meaning: '他者との関係の中で自分を確かめようとする心の動き。' },
    { category: 'identity', trait: '失敗＝価値がないと感じる', meaning: '成果と存在を結びつけるほど真剣に生きてきた証。' },
    { category: 'identity', trait: '過去の自分を許せない', meaning: '過去に対して誠実であろうとする強い責任感。' },
    { category: 'identity', trait: '年齢に縛られてしまう', meaning: '時間や流れを大切に見ている人生観。' },
    { category: 'identity', trait: 'ラベルにしがみついてしまう', meaning: '拠り所を必要とするほど、揺れやすい繊細な魂。' },
    { category: 'identity', trait: '役割を降りるのが怖い', meaning: '誰かの役に立ち続けたいという強い献身性。' },
    { category: 'identity', trait: '何かしていないと存在価値がないと感じる', meaning: '存在そのものの価値をこれから学んでいくプロセスにいる。' },
    { category: 'identity', trait: '休むと罪悪感が出る', meaning: '常に誰かや何かのために動いてきた優しさ。' },
    { category: 'identity', trait: '自分だけ幸せになってはいけないと感じる', meaning: '全体の幸せを願うがゆえに自分を後回しにしてきた慈悲心。' },
    { category: 'identity', trait: '変わることが怖い', meaning: '今まで守ってきたものを大切にしている証拠。' },
    { category: 'identity', trait: '変わらないことが怖い', meaning: '本当は前に進みたいという魂の衝動。' }
  ]
} as const;
